// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetFromFrontendData, GetFromFrontendErrors, GetFromFrontendResponses, GetFromHybridData, GetFromHybridErrors, GetFromHybridResponses, GetFromUmbracoData, GetFromUmbracoErrors, GetFromUmbracoResponses, GetLanguagesData, GetLanguagesErrors, GetLanguagesResponses, SaveDictionaryItemData, SaveDictionaryItemErrors, SaveDictionaryItemResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class CharlieTangoUmbracoTranslationsService {
    public static getFromUmbraco<ThrowOnError extends boolean = false>(options?: Options<GetFromUmbracoData, ThrowOnError>) {
        return (options?.client ?? client).get<GetFromUmbracoResponses, GetFromUmbracoErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracotranslations/api/v1/cms',
            ...options
        });
    }
    
    public static saveDictionaryItem<ThrowOnError extends boolean = false>(options?: Options<SaveDictionaryItemData, ThrowOnError>) {
        return (options?.client ?? client).post<SaveDictionaryItemResponses, SaveDictionaryItemErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracotranslations/api/v1/dictionary',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getFromFrontend<ThrowOnError extends boolean = false>(options?: Options<GetFromFrontendData, ThrowOnError>) {
        return (options?.client ?? client).get<GetFromFrontendResponses, GetFromFrontendErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracotranslations/api/v1/frontend',
            ...options
        });
    }
    
    public static getFromHybrid<ThrowOnError extends boolean = false>(options?: Options<GetFromHybridData, ThrowOnError>) {
        return (options?.client ?? client).get<GetFromHybridResponses, GetFromHybridErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracotranslations/api/v1/hybrid',
            ...options
        });
    }
    
    public static getLanguages<ThrowOnError extends boolean = false>(options?: Options<GetLanguagesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetLanguagesResponses, GetLanguagesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracotranslations/api/v1/languages',
            ...options
        });
    }
}
