// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44313' | (string & {});
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type SaveDictionaryItemRequest = {
    key: string;
    culture: string;
    value: string;
};

export type SaveDictionaryItemResponse = {
    key: string;
    culture: string;
    value: string;
};

export type GetFromUmbracoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracotranslations/api/v1/cms';
};

export type GetFromUmbracoErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetFromUmbracoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SaveDictionaryItemData = {
    body?: SaveDictionaryItemRequest;
    path?: never;
    query?: never;
    url: '/umbraco/umbracotranslations/api/v1/dictionary';
};

export type SaveDictionaryItemErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SaveDictionaryItemResponses = {
    /**
     * OK
     */
    200: SaveDictionaryItemResponse;
};

export type SaveDictionaryItemResponse2 = SaveDictionaryItemResponses[keyof SaveDictionaryItemResponses];

export type GetFromFrontendData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracotranslations/api/v1/frontend';
};

export type GetFromFrontendErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetFromFrontendResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetFromHybridData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracotranslations/api/v1/hybrid';
};

export type GetFromHybridErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetFromHybridResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLanguagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracotranslations/api/v1/languages';
};

export type GetLanguagesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetLanguagesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetLanguagesResponse = GetLanguagesResponses[keyof GetLanguagesResponses];
